<?php


$mike_questions = [
    "@@user@@ invented a new type of modification. Describe it.",
    "Tell the story of how @@user@@ became corrected.",
    "@@user@@ has a broken tracker. How should it be fixed?",
    "@@user@@ has just bought a very civil organisation. Describe how it would be used.",
    "How would @@user@@ treat an early dressing?",
    "Everyone enjoys a theta. What is @@user@@'s like?",
    "@@user@@'s investigator is beneficial. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of lambda. Describe it.",
    "Tell the story of how @@user@@ became realistic.",
    "@@user@@ has a broken saying. How should it be fixed?",
    "@@user@@ has just bought a very everyday mile. Describe how it would be used.",
    "How would @@user@@ treat a parental operation?",
    "Everyone enjoys a syndication. What is @@user@@'s like?",
    "@@user@@'s mixer is generous. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of passion. Describe it.",
    "Tell the story of how @@user@@ became eyed.",
    "@@user@@ has a broken aviation. How should it be fixed?",
    "@@user@@ has just bought a very compressed landing. Describe how it would be used.",
    "How would @@user@@ treat an efficient presence?",
    "Everyone enjoys a convergence. What is @@user@@'s like?",
    "@@user@@'s contracting is rejected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of sociology. Describe it.",
    "Tell the story of how @@user@@ became attempted.",
    "@@user@@ has a broken quantum. How should it be fixed?",
    "@@user@@ has just bought a very newest rec. Describe how it would be used.",
    "How would @@user@@ treat an available biology?",
    "Everyone enjoys a resolution. What is @@user@@'s like?",
    "@@user@@'s removal is destroyed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of reservation. Describe it.",
    "Tell the story of how @@user@@ became pediatric.",
    "@@user@@ has a broken safety. How should it be fixed?",
    "@@user@@ has just bought a very logical palace. Describe how it would be used.",
    "How would @@user@@ treat a determined yahoo?",
    "Everyone enjoys a prisoner. What is @@user@@'s like?",
    "@@user@@'s trout is recommended. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of lightning. Describe it.",
    "Tell the story of how @@user@@ became endangered.",
    "@@user@@ has a broken ciao. How should it be fixed?",
    "@@user@@ has just bought a very animated nirvana. Describe how it would be used.",
    "How would @@user@@ treat a suspended tribute?",
    "Everyone enjoys a monitoring. What is @@user@@'s like?",
    "@@user@@'s salon is chronic. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of palmer. Describe it.",
    "Tell the story of how @@user@@ became registered.",
    "@@user@@ has a broken chapel. How should it be fixed?",
    "@@user@@ has just bought a very oriented membership. Describe how it would be used.",
    "How would @@user@@ treat an untitled violation?",
    "Everyone enjoys a recruitment. What is @@user@@'s like?",
    "@@user@@'s translator is classical. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of investment. Describe it.",
    "Tell the story of how @@user@@ became recovered.",
    "@@user@@ has a broken nat. How should it be fixed?",
    "@@user@@ has just bought a very illegal registry. Describe how it would be used.",
    "How would @@user@@ treat an angry security?",
    "Everyone enjoys a relaxation. What is @@user@@'s like?",
    "@@user@@'s farmer is exciting. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of tradition. Describe it.",
    "Tell the story of how @@user@@ became together.",
    "@@user@@ has a broken implementation. How should it be fixed?",
    "@@user@@ has just bought a very remarkable popularity. Describe how it would be used.",
    "How would @@user@@ treat an interactive combo?",
    "Everyone enjoys a religion. What is @@user@@'s like?",
    "@@user@@'s management is requested. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of hair. Describe it.",
    "Tell the story of how @@user@@ became adjustable.",
    "@@user@@ has a broken child. How should it be fixed?",
    "@@user@@ has just bought a very reliable compliance. Describe how it would be used.",
    "How would @@user@@ treat a discovered basketball?",
    "Everyone enjoys a framing. What is @@user@@'s like?",
    "@@user@@'s genealogy is oriented. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of worcester. Describe it.",
    "Tell the story of how @@user@@ became apparent.",
    "@@user@@ has a broken throat. How should it be fixed?",
    "@@user@@ has just bought a very turned sociology. Describe how it would be used.",
    "How would @@user@@ treat a matching neon?",
    "Everyone enjoys an eau. What is @@user@@'s like?",
    "@@user@@'s catalyst is nationwide. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of minority. Describe it.",
    "Tell the story of how @@user@@ became interactive.",
    "@@user@@ has a broken butterfly. How should it be fixed?",
    "@@user@@ has just bought a very reported definition. Describe how it would be used.",
    "How would @@user@@ treat a happy alcohol?",
    "Everyone enjoys a creature. What is @@user@@'s like?",
    "@@user@@'s digit is removable. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of surgery. Describe it.",
    "Tell the story of how @@user@@ became expected.",
    "@@user@@ has a broken publication. How should it be fixed?",
    "@@user@@ has just bought a very rational door. Describe how it would be used.",
    "How would @@user@@ treat an awesome navy?",
    "Everyone enjoys a transition. What is @@user@@'s like?",
    "@@user@@'s algebra is cellular. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of ordering. Describe it.",
    "Tell the story of how @@user@@ became magnetic.",
    "@@user@@ has a broken pork. How should it be fixed?",
    "@@user@@ has just bought a very promotional babe. Describe how it would be used.",
    "How would @@user@@ treat a traditional tractor?",
    "Everyone enjoys a comparison. What is @@user@@'s like?",
    "@@user@@'s doctrine is painful. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of tradition. Describe it.",
    "Tell the story of how @@user@@ became earlier.",
    "@@user@@ has a broken someone. How should it be fixed?",
    "@@user@@ has just bought a very ago reputation. Describe how it would be used.",
    "How would @@user@@ treat a worldwide belle?",
    "Everyone enjoys a charlotte. What is @@user@@'s like?",
    "@@user@@'s pastor is literary. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of intention. Describe it.",
    "Tell the story of how @@user@@ became graphical.",
    "@@user@@ has a broken quantity. How should it be fixed?",
    "@@user@@ has just bought a very terrible lender. Describe how it would be used.",
    "How would @@user@@ treat an otherwise survival?",
    "Everyone enjoys a manager. What is @@user@@'s like?",
    "@@user@@'s erotica is registered. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of implementation. Describe it.",
    "Tell the story of how @@user@@ became dispatched.",
    "@@user@@ has a broken notification. How should it be fixed?",
    "@@user@@ has just bought a very behavioral policy. Describe how it would be used.",
    "How would @@user@@ treat an inappropriate controversy?",
    "Everyone enjoys a legacy. What is @@user@@'s like?",
    "@@user@@'s fabric is awful. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of developer. Describe it.",
    "Tell the story of how @@user@@ became atomic.",
    "@@user@@ has a broken timothy. How should it be fixed?",
    "@@user@@ has just bought a very informal transportation. Describe how it would be used.",
    "How would @@user@@ treat a wicked accessibility?",
    "Everyone enjoys a footage. What is @@user@@'s like?",
    "@@user@@'s collecting is both. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of legislature. Describe it.",
    "Tell the story of how @@user@@ became urban.",
    "@@user@@ has a broken procurement. How should it be fixed?",
    "@@user@@ has just bought a very happy bee. Describe how it would be used.",
    "How would @@user@@ treat an earned achievement?",
    "Everyone enjoys a microphone. What is @@user@@'s like?",
    "@@user@@'s shipment is affected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of payday. Describe it.",
    "Tell the story of how @@user@@ became trained.",
    "@@user@@ has a broken missile. How should it be fixed?",
    "@@user@@ has just bought a very subtle relief. Describe how it would be used.",
    "How would @@user@@ treat an electronic energy?",
    "Everyone enjoys an eric. What is @@user@@'s like?",
    "@@user@@'s area is incorporated. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of guitar. Describe it.",
    "Tell the story of how @@user@@ became informal.",
    "@@user@@ has a broken achievement. How should it be fixed?",
    "@@user@@ has just bought a very incorporated recreation. Describe how it would be used.",
    "How would @@user@@ treat a ranked ballet?",
    "Everyone enjoys an usage. What is @@user@@'s like?",
    "@@user@@'s communication is tested. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of reliance. Describe it.",
    "Tell the story of how @@user@@ became angry.",
    "@@user@@ has a broken song. How should it be fixed?",
    "@@user@@ has just bought a very cultural warranty. Describe how it would be used.",
    "How would @@user@@ treat an innovative spirituality?",
    "Everyone enjoys a timer. What is @@user@@'s like?",
    "@@user@@'s rendering is informative. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of mart. Describe it.",
    "Tell the story of how @@user@@ became exposed.",
    "@@user@@ has a broken amplifier. How should it be fixed?",
    "@@user@@ has just bought a very huge baseball. Describe how it would be used.",
    "How would @@user@@ treat an employed occurrence?",
    "Everyone enjoys a variance. What is @@user@@'s like?",
    "@@user@@'s museum is anal. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of industry. Describe it.",
    "Tell the story of how @@user@@ became incredible.",
    "@@user@@ has a broken producer. How should it be fixed?",
    "@@user@@ has just bought a very affecting ensemble. Describe how it would be used.",
    "How would @@user@@ treat a both tournament?",
    "Everyone enjoys a vertex. What is @@user@@'s like?",
    "@@user@@'s underwear is incomplete. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of plaza. Describe it.",
    "Tell the story of how @@user@@ became alleged.",
    "@@user@@ has a broken creature. How should it be fixed?",
    "@@user@@ has just bought a very non preference. Describe how it would be used.",
    "How would @@user@@ treat an infectious violation?",
    "Everyone enjoys a rug. What is @@user@@'s like?",
    "@@user@@'s conspiracy is various. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of forestry. Describe it.",
    "Tell the story of how @@user@@ became agricultural.",
    "@@user@@ has a broken theta. How should it be fixed?",
    "@@user@@ has just bought a very organizational data. Describe how it would be used.",
    "How would @@user@@ treat a historical specification?",
    "Everyone enjoys an empire. What is @@user@@'s like?",
    "@@user@@'s supplier is delayed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of doll. Describe it.",
    "Tell the story of how @@user@@ became satisfactory.",
    "@@user@@ has a broken thumbnail. How should it be fixed?",
    "@@user@@ has just bought a very dangerous reunion. Describe how it would be used.",
    "How would @@user@@ treat a funky person?",
    "Everyone enjoys an aye. What is @@user@@'s like?",
    "@@user@@'s mailman is inserted. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of attitude. Describe it.",
    "Tell the story of how @@user@@ became handy.",
    "@@user@@ has a broken computation. How should it be fixed?",
    "@@user@@ has just bought a very relevant grammar. Describe how it would be used.",
    "How would @@user@@ treat an unexpected prince?",
    "Everyone enjoys a yesterday. What is @@user@@'s like?",
    "@@user@@'s supplier is naked. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of diameter. Describe it.",
    "Tell the story of how @@user@@ became early.",
    "@@user@@ has a broken government. How should it be fixed?",
    "@@user@@ has just bought a very recent population. Describe how it would be used.",
    "How would @@user@@ treat a southern glen?",
    "Everyone enjoys a florence. What is @@user@@'s like?",
    "@@user@@'s agent is artistic. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of computer. Describe it.",
    "Tell the story of how @@user@@ became authorized.",
    "@@user@@ has a broken problem. How should it be fixed?",
    "@@user@@ has just bought a very displayed emerald. Describe how it would be used.",
    "How would @@user@@ treat a furnished conservation?",
    "Everyone enjoys a herb. What is @@user@@'s like?",
    "@@user@@'s payday is dimensional. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of era. Describe it.",
    "Tell the story of how @@user@@ became maritime.",
    "@@user@@ has a broken achievement. How should it be fixed?",
    "@@user@@ has just bought a very awful prediction. Describe how it would be used.",
    "How would @@user@@ treat a lazy preservation?",
    "Everyone enjoys a poet. What is @@user@@'s like?",
    "@@user@@'s camera is other. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of exploration. Describe it.",
    "Tell the story of how @@user@@ became according.",
    "@@user@@ has a broken tribute. How should it be fixed?",
    "@@user@@ has just bought a very cleared reading. Describe how it would be used.",
    "How would @@user@@ treat an architectural blade?",
    "Everyone enjoys a realm. What is @@user@@'s like?",
    "@@user@@'s investigation is administrative. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of comedy. Describe it.",
    "Tell the story of how @@user@@ became prepared.",
    "@@user@@ has a broken cigarette. How should it be fixed?",
    "@@user@@ has just bought a very martial jaguar. Describe how it would be used.",
    "How would @@user@@ treat a valued helmet?",
    "Everyone enjoys an ensemble. What is @@user@@'s like?",
    "@@user@@'s prophet is viral. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of assurance. Describe it.",
    "Tell the story of how @@user@@ became tony.",
    "@@user@@ has a broken thou. How should it be fixed?",
    "@@user@@ has just bought a very unsigned something. Describe how it would be used.",
    "How would @@user@@ treat a pursuant yea?",
    "Everyone enjoys a kingdom. What is @@user@@'s like?",
    "@@user@@'s equipment is dumb. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of induction. Describe it.",
    "Tell the story of how @@user@@ became minimal.",
    "@@user@@ has a broken steering. How should it be fixed?",
    "@@user@@ has just bought a very comfortable institution. Describe how it would be used.",
    "How would @@user@@ treat a metallic breath?",
    "Everyone enjoys a toolbox. What is @@user@@'s like?",
    "@@user@@'s lid is rolled. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of symposium. Describe it.",
    "Tell the story of how @@user@@ became greater.",
    "@@user@@ has a broken assembly. How should it be fixed?",
    "@@user@@ has just bought a very eastern ballet. Describe how it would be used.",
    "How would @@user@@ treat a whatever enclosure?",
    "Everyone enjoys a relationship. What is @@user@@'s like?",
    "@@user@@'s crime is repeated. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of franklin. Describe it.",
    "Tell the story of how @@user@@ became existing.",
    "@@user@@ has a broken equipment. How should it be fixed?",
    "@@user@@ has just bought a very strong module. Describe how it would be used.",
    "How would @@user@@ treat an alive hair?",
    "Everyone enjoys an orientation. What is @@user@@'s like?",
    "@@user@@'s holland is considerable. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of framework. Describe it.",
    "Tell the story of how @@user@@ became nutritional.",
    "@@user@@ has a broken panama. How should it be fixed?",
    "@@user@@ has just bought a very increasing investigator. Describe how it would be used.",
    "How would @@user@@ treat an expected toolbox?",
    "Everyone enjoys a zoo. What is @@user@@'s like?",
    "@@user@@'s poetry is cellular. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of waiver. Describe it.",
    "Tell the story of how @@user@@ became applied.",
    "@@user@@ has a broken constraint. How should it be fixed?",
    "@@user@@ has just bought a very ongoing discrimination. Describe how it would be used.",
    "How would @@user@@ treat an expressed devel?",
    "Everyone enjoys a department. What is @@user@@'s like?",
    "@@user@@'s practitioner is meaningful. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of citizen. Describe it.",
    "Tell the story of how @@user@@ became endorsed.",
    "@@user@@ has a broken specification. How should it be fixed?",
    "@@user@@ has just bought a very persistent reflection. Describe how it would be used.",
    "How would @@user@@ treat a historical supervisor?",
    "Everyone enjoys a newspaper. What is @@user@@'s like?",
    "@@user@@'s tiger is fabulous. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of transcript. Describe it.",
    "Tell the story of how @@user@@ became additional.",
    "@@user@@ has a broken senator. How should it be fixed?",
    "@@user@@ has just bought a very eternal pottery. Describe how it would be used.",
    "How would @@user@@ treat an elementary grammar?",
    "Everyone enjoys an interface. What is @@user@@'s like?",
    "@@user@@'s horizon is terrible. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of engagement. Describe it.",
    "Tell the story of how @@user@@ became strong.",
    "@@user@@ has a broken planet. How should it be fixed?",
    "@@user@@ has just bought a very significant attraction. Describe how it would be used.",
    "How would @@user@@ treat a medieval election?",
    "Everyone enjoys a momentum. What is @@user@@'s like?",
    "@@user@@'s cemetery is altered. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of someone. Describe it.",
    "Tell the story of how @@user@@ became forced.",
    "@@user@@ has a broken diesel. How should it be fixed?",
    "@@user@@ has just bought a very outdoor terry. Describe how it would be used.",
    "How would @@user@@ treat a turned violin?",
    "Everyone enjoys an intro. What is @@user@@'s like?",
    "@@user@@'s curriculum is closed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of relationship. Describe it.",
    "Tell the story of how @@user@@ became pleasant.",
    "@@user@@ has a broken browser. How should it be fixed?",
    "@@user@@ has just bought a very matched student. Describe how it would be used.",
    "How would @@user@@ treat an extraordinary python?",
    "Everyone enjoys a beth. What is @@user@@'s like?",
    "@@user@@'s bracelet is deferred. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of hydrogen. Describe it.",
    "Tell the story of how @@user@@ became continuous.",
    "@@user@@ has a broken enlargement. How should it be fixed?",
    "@@user@@ has just bought a very numerical insurance. Describe how it would be used.",
    "How would @@user@@ treat a grown citizenship?",
    "Everyone enjoys a til. What is @@user@@'s like?",
    "@@user@@'s property is incomplete. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of advertising. Describe it.",
    "Tell the story of how @@user@@ became implemented.",
    "@@user@@ has a broken fusion. How should it be fixed?",
    "@@user@@ has just bought a very bigger album. Describe how it would be used.",
    "How would @@user@@ treat a predicted possession?",
    "Everyone enjoys a multimedia. What is @@user@@'s like?",
    "@@user@@'s legend is disappointed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of ensemble. Describe it.",
    "Tell the story of how @@user@@ became naked.",
    "@@user@@ has a broken gnu. How should it be fixed?",
    "@@user@@ has just bought a very gorgeous ala. Describe how it would be used.",
    "How would @@user@@ treat a formed journalism?",
    "Everyone enjoys a mali. What is @@user@@'s like?",
    "@@user@@'s colon is identical. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of butler. Describe it.",
    "Tell the story of how @@user@@ became honest.",
    "@@user@@ has a broken victory. How should it be fixed?",
    "@@user@@ has just bought a very affected incidence. Describe how it would be used.",
    "How would @@user@@ treat a twisted survival?",
    "Everyone enjoys an incest. What is @@user@@'s like?",
    "@@user@@'s nature is drawn. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of arrangement. Describe it.",
    "Tell the story of how @@user@@ became several.",
    "@@user@@ has a broken particle. How should it be fixed?",
    "@@user@@ has just bought a very interesting bingo. Describe how it would be used.",
    "How would @@user@@ treat a robust consumption?",
    "Everyone enjoys a chest. What is @@user@@'s like?",
    "@@user@@'s legacy is satisfactory. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of width. Describe it.",
    "Tell the story of how @@user@@ became dedicated.",
    "@@user@@ has a broken kitchen. How should it be fixed?",
    "@@user@@ has just bought a very predicted multimedia. Describe how it would be used.",
    "How would @@user@@ treat a geographic disease?",
    "Everyone enjoys a printer. What is @@user@@'s like?",
    "@@user@@'s chile is miscellaneous. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of resistance. Describe it.",
    "Tell the story of how @@user@@ became dangerous.",
    "@@user@@ has a broken syntax. How should it be fixed?",
    "@@user@@ has just bought a very retained essence. Describe how it would be used.",
    "How would @@user@@ treat a scary dod?",
    "Everyone enjoys a methodology. What is @@user@@'s like?",
    "@@user@@'s transparency is obvious. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of sensitivity. Describe it.",
    "Tell the story of how @@user@@ became popular.",
    "@@user@@ has a broken something. How should it be fixed?",
    "@@user@@ has just bought a very ordered ozone. Describe how it would be used.",
    "How would @@user@@ treat a grateful membrane?",
    "Everyone enjoys a transaction. What is @@user@@'s like?",
    "@@user@@'s organ is varied. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of journalist. Describe it.",
    "Tell the story of how @@user@@ became under.",
    "@@user@@ has a broken bureau. How should it be fixed?",
    "@@user@@ has just bought a very bizarre silicon. Describe how it would be used.",
    "How would @@user@@ treat an electronic gene?",
    "Everyone enjoys a hero. What is @@user@@'s like?",
    "@@user@@'s monitoring is statewide. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of authority. Describe it.",
    "Tell the story of how @@user@@ became emotional.",
    "@@user@@ has a broken entrepreneur. How should it be fixed?",
    "@@user@@ has just bought a very alike burner. Describe how it would be used.",
    "How would @@user@@ treat a solar adaptor?",
    "Everyone enjoys a death. What is @@user@@'s like?",
    "@@user@@'s formula is represented. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of grocery. Describe it.",
    "Tell the story of how @@user@@ became anonymous.",
    "@@user@@ has a broken florist. How should it be fixed?",
    "@@user@@ has just bought a very allowed missile. Describe how it would be used.",
    "How would @@user@@ treat a hourly expansion?",
    "Everyone enjoys a corporation. What is @@user@@'s like?",
    "@@user@@'s humidity is abroad. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of estate. Describe it.",
    "Tell the story of how @@user@@ became adjusted.",
    "@@user@@ has a broken consortium. How should it be fixed?",
    "@@user@@ has just bought a very nasty pastor. Describe how it would be used.",
    "How would @@user@@ treat an excited glucose?",
    "Everyone enjoys a moment. What is @@user@@'s like?",
    "@@user@@'s clothing is disturbed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of marsh. Describe it.",
    "Tell the story of how @@user@@ became alone.",
    "@@user@@ has a broken confidentiality. How should it be fixed?",
    "@@user@@ has just bought a very generic ide. Describe how it would be used.",
    "How would @@user@@ treat an experimental nylon?",
    "Everyone enjoys a removal. What is @@user@@'s like?",
    "@@user@@'s thanksgiving is specialized. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of pathology. Describe it.",
    "Tell the story of how @@user@@ became unnecessary.",
    "@@user@@ has a broken science. How should it be fixed?",
    "@@user@@ has just bought a very suited locale. Describe how it would be used.",
    "How would @@user@@ treat a related attitude?",
    "Everyone enjoys a til. What is @@user@@'s like?",
    "@@user@@'s beginner is determined. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of reliance. Describe it.",
    "Tell the story of how @@user@@ became regardless.",
    "@@user@@ has a broken constitution. How should it be fixed?",
    "@@user@@ has just bought a very handy classification. Describe how it would be used.",
    "How would @@user@@ treat a matching tonight?",
    "Everyone enjoys an accounting. What is @@user@@'s like?",
    "@@user@@'s somebody is tiny. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of canyon. Describe it.",
    "Tell the story of how @@user@@ became elementary.",
    "@@user@@ has a broken acre. How should it be fixed?",
    "@@user@@ has just bought a very specialized breath. Describe how it would be used.",
    "How would @@user@@ treat an abroad villa?",
    "Everyone enjoys a paradise. What is @@user@@'s like?",
    "@@user@@'s polo is vocational. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of enrollment. Describe it.",
    "Tell the story of how @@user@@ became included.",
    "@@user@@ has a broken duration. How should it be fixed?",
    "@@user@@ has just bought a very covered shareware. Describe how it would be used.",
    "How would @@user@@ treat a marked carter?",
    "Everyone enjoys a carrier. What is @@user@@'s like?",
    "@@user@@'s reservoir is removable. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of sen. Describe it.",
    "Tell the story of how @@user@@ became adjustable.",
    "@@user@@ has a broken viewer. How should it be fixed?",
    "@@user@@ has just bought a very repeated trio. Describe how it would be used.",
    "How would @@user@@ treat a picked director?",
    "Everyone enjoys a coalition. What is @@user@@'s like?",
    "@@user@@'s tribunal is graduated. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of growth. Describe it.",
    "Tell the story of how @@user@@ became cultural.",
    "@@user@@ has a broken pathology. How should it be fixed?",
    "@@user@@ has just bought a very popular disclosure. Describe how it would be used.",
    "How would @@user@@ treat a similar fibre?",
    "Everyone enjoys an investigation. What is @@user@@'s like?",
    "@@user@@'s contracting is another. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of vibrator. Describe it.",
    "Tell the story of how @@user@@ became informative.",
    "@@user@@ has a broken rand. How should it be fixed?",
    "@@user@@ has just bought a very honest terror. Describe how it would be used.",
    "How would @@user@@ treat a recreational sofa?",
    "Everyone enjoys a creativity. What is @@user@@'s like?",
    "@@user@@'s psychology is mysterious. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of candidate. Describe it.",
    "Tell the story of how @@user@@ became mailed.",
    "@@user@@ has a broken reminder. How should it be fixed?",
    "@@user@@ has just bought a very alphabetical killer. Describe how it would be used.",
    "How would @@user@@ treat a removed dude?",
    "Everyone enjoys a sunshine. What is @@user@@'s like?",
    "@@user@@'s math is dimensional. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of how. Describe it.",
    "Tell the story of how @@user@@ became highest.",
    "@@user@@ has a broken carter. How should it be fixed?",
    "@@user@@ has just bought a very reserved monte. Describe how it would be used.",
    "How would @@user@@ treat an each weapon?",
    "Everyone enjoys a practitioner. What is @@user@@'s like?",
    "@@user@@'s messenger is biggest. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of tourism. Describe it.",
    "Tell the story of how @@user@@ became geological.",
    "@@user@@ has a broken perry. How should it be fixed?",
    "@@user@@ has just bought a very occasional exemption. Describe how it would be used.",
    "How would @@user@@ treat a bibliographic why?",
    "Everyone enjoys a bride. What is @@user@@'s like?",
    "@@user@@'s nova is relevant. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of syndication. Describe it.",
    "Tell the story of how @@user@@ became congressional.",
    "@@user@@ has a broken difficulty. How should it be fixed?",
    "@@user@@ has just bought a very obvious murphy. Describe how it would be used.",
    "How would @@user@@ treat a subtle consumer?",
    "Everyone enjoys an inflation. What is @@user@@'s like?",
    "@@user@@'s wisdom is corrected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of theta. Describe it.",
    "Tell the story of how @@user@@ became micro.",
    "@@user@@ has a broken helicopter. How should it be fixed?",
    "@@user@@ has just bought a very fabulous maker. Describe how it would be used.",
    "How would @@user@@ treat a squirting gene?",
    "Everyone enjoys a month. What is @@user@@'s like?",
    "@@user@@'s comedy is successful. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of tuner. Describe it.",
    "Tell the story of how @@user@@ became figured.",
    "@@user@@ has a broken celebrity. How should it be fixed?",
    "@@user@@ has just bought a very backed pursuit. Describe how it would be used.",
    "How would @@user@@ treat a failed personality?",
    "Everyone enjoys an integer. What is @@user@@'s like?",
    "@@user@@'s library is according. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of matrix. Describe it.",
    "Tell the story of how @@user@@ became subsequent.",
    "@@user@@ has a broken vegetation. How should it be fixed?",
    "@@user@@ has just bought a very impaired criticism. Describe how it would be used.",
    "How would @@user@@ treat a conscious acceptance?",
    "Everyone enjoys a cad. What is @@user@@'s like?",
    "@@user@@'s resolution is advisory. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of version. Describe it.",
    "Tell the story of how @@user@@ became merry.",
    "@@user@@ has a broken poetry. How should it be fixed?",
    "@@user@@ has just bought a very geographical probability. Describe how it would be used.",
    "How would @@user@@ treat a difficult silicon?",
    "Everyone enjoys a mounting. What is @@user@@'s like?",
    "@@user@@'s thou is longest. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of conducting. Describe it.",
    "Tell the story of how @@user@@ became detailed.",
    "@@user@@ has a broken prediction. How should it be fixed?",
    "@@user@@ has just bought a very resulting locale. Describe how it would be used.",
    "How would @@user@@ treat an alphabetical protein?",
    "Everyone enjoys a sheep. What is @@user@@'s like?",
    "@@user@@'s logging is related. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of joe. Describe it.",
    "Tell the story of how @@user@@ became each.",
    "@@user@@ has a broken episode. How should it be fixed?",
    "@@user@@ has just bought a very animated sale. Describe how it would be used.",
    "How would @@user@@ treat a contained combo?",
    "Everyone enjoys a physiology. What is @@user@@'s like?",
    "@@user@@'s beta is detected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of getting. Describe it.",
    "Tell the story of how @@user@@ became floating.",
    "@@user@@ has a broken grocery. How should it be fixed?",
    "@@user@@ has just bought a very wicked legend. Describe how it would be used.",
    "How would @@user@@ treat a fabulous workstation?",
    "Everyone enjoys a connection. What is @@user@@'s like?",
    "@@user@@'s mood is stunning. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of recommendation. Describe it.",
    "Tell the story of how @@user@@ became lucky.",
    "@@user@@ has a broken chi. How should it be fixed?",
    "@@user@@ has just bought a very resulting inclusion. Describe how it would be used.",
    "How would @@user@@ treat a such heading?",
    "Everyone enjoys a lib. What is @@user@@'s like?",
    "@@user@@'s rehabilitation is statewide. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of judgment. Describe it.",
    "Tell the story of how @@user@@ became decided.",
    "@@user@@ has a broken requirement. How should it be fixed?",
    "@@user@@ has just bought a very experienced timer. Describe how it would be used.",
    "How would @@user@@ treat a distant week?",
    "Everyone enjoys a context. What is @@user@@'s like?",
    "@@user@@'s imagination is every. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of cult. Describe it.",
    "Tell the story of how @@user@@ became violent.",
    "@@user@@ has a broken legislation. How should it be fixed?",
    "@@user@@ has just bought a very prepaid theater. Describe how it would be used.",
    "How would @@user@@ treat an efficient greeting?",
    "Everyone enjoys a century. What is @@user@@'s like?",
    "@@user@@'s reconstruction is numerous. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of enquiry. Describe it.",
    "Tell the story of how @@user@@ became lite.",
    "@@user@@ has a broken zen. How should it be fixed?",
    "@@user@@ has just bought a very behavioral marking. Describe how it would be used.",
    "How would @@user@@ treat a linked personality?",
    "Everyone enjoys a membership. What is @@user@@'s like?",
    "@@user@@'s engine is aware. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of starter. Describe it.",
    "Tell the story of how @@user@@ became worked.",
    "@@user@@ has a broken car. How should it be fixed?",
    "@@user@@ has just bought a very packed municipality. Describe how it would be used.",
    "How would @@user@@ treat an accepted men?",
    "Everyone enjoys a shareware. What is @@user@@'s like?",
    "@@user@@'s steering is relevant. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of banana. Describe it.",
    "Tell the story of how @@user@@ became experimental.",
    "@@user@@ has a broken heading. How should it be fixed?",
    "@@user@@ has just bought a very across township. Describe how it would be used.",
    "How would @@user@@ treat a largest heaven?",
    "Everyone enjoys an orgasm. What is @@user@@'s like?",
    "@@user@@'s math is evident. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of adoption. Describe it.",
    "Tell the story of how @@user@@ became occupied.",
    "@@user@@ has a broken cliff. How should it be fixed?",
    "@@user@@ has just bought a very realistic herb. Describe how it would be used.",
    "How would @@user@@ treat an available infrastructure?",
    "Everyone enjoys a parking. What is @@user@@'s like?",
    "@@user@@'s nil is connected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of camera. Describe it.",
    "Tell the story of how @@user@@ became allied.",
    "@@user@@ has a broken precision. How should it be fixed?",
    "@@user@@ has just bought a very upcoming mapping. Describe how it would be used.",
    "How would @@user@@ treat an every sheriff?",
    "Everyone enjoys an inspiration. What is @@user@@'s like?",
    "@@user@@'s attention is extended. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of ozone. Describe it.",
    "Tell the story of how @@user@@ became ahead.",
    "@@user@@ has a broken vampire. How should it be fixed?",
    "@@user@@ has just bought a very expanding coaching. Describe how it would be used.",
    "How would @@user@@ treat a pediatric actor?",
    "Everyone enjoys a problem. What is @@user@@'s like?",
    "@@user@@'s librarian is tested. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of programmer. Describe it.",
    "Tell the story of how @@user@@ became destroyed.",
    "@@user@@ has a broken glossary. How should it be fixed?",
    "@@user@@ has just bought a very accepted glucose. Describe how it would be used.",
    "How would @@user@@ treat a shared suspension?",
    "Everyone enjoys an outcome. What is @@user@@'s like?",
    "@@user@@'s member is attractive. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of aerospace. Describe it.",
    "Tell the story of how @@user@@ became historical.",
    "@@user@@ has a broken identification. How should it be fixed?",
    "@@user@@ has just bought a very affecting meanwhile. Describe how it would be used.",
    "How would @@user@@ treat an infectious valley?",
    "Everyone enjoys a problem. What is @@user@@'s like?",
    "@@user@@'s sept is passed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of recreation. Describe it.",
    "Tell the story of how @@user@@ became converted.",
    "@@user@@ has a broken embassy. How should it be fixed?",
    "@@user@@ has just bought a very prospective allergy. Describe how it would be used.",
    "How would @@user@@ treat a supposed salon?",
    "Everyone enjoys a nil. What is @@user@@'s like?",
    "@@user@@'s hunting is deferred. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of journal. Describe it.",
    "Tell the story of how @@user@@ became assumed.",
    "@@user@@ has a broken personality. How should it be fixed?",
    "@@user@@ has just bought a very treated necessity. Describe how it would be used.",
    "How would @@user@@ treat a threatening python?",
    "Everyone enjoys a providence. What is @@user@@'s like?",
    "@@user@@'s vendor is transparent. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of uncertainty. Describe it.",
    "Tell the story of how @@user@@ became qualified.",
    "@@user@@ has a broken training. How should it be fixed?",
    "@@user@@ has just bought a very trusted she. Describe how it would be used.",
    "How would @@user@@ treat an unable terminology?",
    "Everyone enjoys a replication. What is @@user@@'s like?",
    "@@user@@'s governor is infectious. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of beast. Describe it.",
    "Tell the story of how @@user@@ became apparent.",
    "@@user@@ has a broken incest. How should it be fixed?",
    "@@user@@ has just bought a very inherited onion. Describe how it would be used.",
    "How would @@user@@ treat an intense classification?",
    "Everyone enjoys a filename. What is @@user@@'s like?",
    "@@user@@'s landing is nearest. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of phi. Describe it.",
    "Tell the story of how @@user@@ became behavioral.",
    "@@user@@ has a broken tyler. How should it be fixed?",
    "@@user@@ has just bought a very challenging playboy. Describe how it would be used.",
    "How would @@user@@ treat a horny evanescence?",
    "Everyone enjoys a traveler. What is @@user@@'s like?",
    "@@user@@'s newton is global. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of compensation. Describe it.",
    "Tell the story of how @@user@@ became called.",
    "@@user@@ has a broken highway. How should it be fixed?",
    "@@user@@ has just bought a very joined definition. Describe how it would be used.",
    "How would @@user@@ treat an experienced admin?",
    "Everyone enjoys a checkout. What is @@user@@'s like?",
    "@@user@@'s auto is ripe. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of database. Describe it.",
    "Tell the story of how @@user@@ became intense.",
    "@@user@@ has a broken cooperation. How should it be fixed?",
    "@@user@@ has just bought a very animated sheriff. Describe how it would be used.",
    "How would @@user@@ treat an antivirus celebration?",
    "Everyone enjoys a freedom. What is @@user@@'s like?",
    "@@user@@'s accuracy is amazing. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of joining. Describe it.",
    "Tell the story of how @@user@@ became magnetic.",
    "@@user@@ has a broken recognition. How should it be fixed?",
    "@@user@@ has just bought a very suspended biz. Describe how it would be used.",
    "How would @@user@@ treat a stopped duration?",
    "Everyone enjoys a perception. What is @@user@@'s like?",
    "@@user@@'s airport is painful. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of magnet. Describe it.",
    "Tell the story of how @@user@@ became cumulative.",
    "@@user@@ has a broken commerce. How should it be fixed?",
    "@@user@@ has just bought a very precise subscription. Describe how it would be used.",
    "How would @@user@@ treat a sure information?",
    "Everyone enjoys an interaction. What is @@user@@'s like?",
    "@@user@@'s teaching is often. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of religion. Describe it.",
    "Tell the story of how @@user@@ became rural.",
    "@@user@@ has a broken tractor. How should it be fixed?",
    "@@user@@ has just bought a very mental workplace. Describe how it would be used.",
    "How would @@user@@ treat a delayed workstation?",
    "Everyone enjoys an absence. What is @@user@@'s like?",
    "@@user@@'s marina is dated. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of infrastructure. Describe it.",
    "Tell the story of how @@user@@ became earliest.",
    "@@user@@ has a broken watching. How should it be fixed?",
    "@@user@@ has just bought a very introductory tommy. Describe how it would be used.",
    "How would @@user@@ treat a dangerous watt?",
    "Everyone enjoys a transcript. What is @@user@@'s like?",
    "@@user@@'s hub is sensitive. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of porter. Describe it.",
    "Tell the story of how @@user@@ became decided.",
    "@@user@@ has a broken detection. How should it be fixed?",
    "@@user@@ has just bought a very immediate animation. Describe how it would be used.",
    "How would @@user@@ treat an exposed helping?",
    "Everyone enjoys a sept. What is @@user@@'s like?",
    "@@user@@'s receiver is concerning. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of method. Describe it.",
    "Tell the story of how @@user@@ became extraordinary.",
    "@@user@@ has a broken disease. How should it be fixed?",
    "@@user@@ has just bought a very spatial temperature. Describe how it would be used.",
    "How would @@user@@ treat a distinct reaction?",
    "Everyone enjoys a jersey. What is @@user@@'s like?",
    "@@user@@'s expertise is resolved. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of anxiety. Describe it.",
    "Tell the story of how @@user@@ became electronic.",
    "@@user@@ has a broken momentum. How should it be fixed?",
    "@@user@@ has just bought a very industrial jane. Describe how it would be used.",
    "How would @@user@@ treat an intense pst?",
    "Everyone enjoys a welding. What is @@user@@'s like?",
    "@@user@@'s tumor is suspected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of engagement. Describe it.",
    "Tell the story of how @@user@@ became regardless.",
    "@@user@@ has a broken regime. How should it be fixed?",
    "@@user@@ has just bought a very postal album. Describe how it would be used.",
    "How would @@user@@ treat a handed poverty?",
    "Everyone enjoys an invasion. What is @@user@@'s like?",
    "@@user@@'s voyeur is hazardous. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of village. Describe it.",
    "Tell the story of how @@user@@ became some.",
    "@@user@@ has a broken chancellor. How should it be fixed?",
    "@@user@@ has just bought a very different arrival. Describe how it would be used.",
    "How would @@user@@ treat an alpine prince?",
    "Everyone enjoys a quantum. What is @@user@@'s like?",
    "@@user@@'s deviation is attached. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of baker. Describe it.",
    "Tell the story of how @@user@@ became creative.",
    "@@user@@ has a broken diary. How should it be fixed?",
    "@@user@@ has just bought a very genuine editing. Describe how it would be used.",
    "How would @@user@@ treat a dense frequency?",
    "Everyone enjoys a firewall. What is @@user@@'s like?",
    "@@user@@'s walker is acceptable. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of enlargement. Describe it.",
    "Tell the story of how @@user@@ became powered.",
    "@@user@@ has a broken likelihood. How should it be fixed?",
    "@@user@@ has just bought a very discovered reunion. Describe how it would be used.",
    "How would @@user@@ treat a worried panama?",
    "Everyone enjoys a dragon. What is @@user@@'s like?",
    "@@user@@'s bishop is unlimited. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of legislature. Describe it.",
    "Tell the story of how @@user@@ became identical.",
    "@@user@@ has a broken laura. How should it be fixed?",
    "@@user@@ has just bought a very informational century. Describe how it would be used.",
    "How would @@user@@ treat a legal drama?",
    "Everyone enjoys a chile. What is @@user@@'s like?",
    "@@user@@'s tract is established. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of cent. Describe it.",
    "Tell the story of how @@user@@ became directed.",
    "@@user@@ has a broken enforcement. How should it be fixed?",
    "@@user@@ has just bought a very qualified onion. Describe how it would be used.",
    "How would @@user@@ treat a graphic grad?",
    "Everyone enjoys a lawsuit. What is @@user@@'s like?",
    "@@user@@'s sofa is precise. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of nursing. Describe it.",
    "Tell the story of how @@user@@ became dressed.",
    "@@user@@ has a broken deer. How should it be fixed?",
    "@@user@@ has just bought a very tropical literature. Describe how it would be used.",
    "How would @@user@@ treat an earned diving?",
    "Everyone enjoys a miracle. What is @@user@@'s like?",
    "@@user@@'s continuity is fuzzy. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of jill. Describe it.",
    "Tell the story of how @@user@@ became forced.",
    "@@user@@ has a broken argument. How should it be fixed?",
    "@@user@@ has just bought a very complimentary surrey. Describe how it would be used.",
    "How would @@user@@ treat an efficient interpretation?",
    "Everyone enjoys a trout. What is @@user@@'s like?",
    "@@user@@'s carter is about. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of president. Describe it.",
    "Tell the story of how @@user@@ became photographic.",
    "@@user@@ has a broken viewing. How should it be fixed?",
    "@@user@@ has just bought a very intelligent maintenance. Describe how it would be used.",
    "How would @@user@@ treat a computational poly?",
    "Everyone enjoys a performance. What is @@user@@'s like?",
    "@@user@@'s gentleman is horny. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of gale. Describe it.",
    "Tell the story of how @@user@@ became famous.",
    "@@user@@ has a broken expansion. How should it be fixed?",
    "@@user@@ has just bought a very cardiovascular humidity. Describe how it would be used.",
    "How would @@user@@ treat a naval liability?",
    "Everyone enjoys an induction. What is @@user@@'s like?",
    "@@user@@'s parish is backed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of significance. Describe it.",
    "Tell the story of how @@user@@ became registered.",
    "@@user@@ has a broken coupon. How should it be fixed?",
    "@@user@@ has just bought a very promotional lender. Describe how it would be used.",
    "How would @@user@@ treat a deadly tiger?",
    "Everyone enjoys an angel. What is @@user@@'s like?",
    "@@user@@'s attendance is often. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of folder. Describe it.",
    "Tell the story of how @@user@@ became compatible.",
    "@@user@@ has a broken replacement. How should it be fixed?",
    "@@user@@ has just bought a very intense worcester. Describe how it would be used.",
    "How would @@user@@ treat an incorporated department?",
    "Everyone enjoys a validation. What is @@user@@'s like?",
    "@@user@@'s ton is expensive. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of privacy. Describe it.",
    "Tell the story of how @@user@@ became incomplete.",
    "@@user@@ has a broken liberty. How should it be fixed?",
    "@@user@@ has just bought a very worldwide citizenship. Describe how it would be used.",
    "How would @@user@@ treat a harmful checkout?",
    "Everyone enjoys a dollar. What is @@user@@'s like?",
    "@@user@@'s adaptor is simplified. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of appearance. Describe it.",
    "Tell the story of how @@user@@ became edited.",
    "@@user@@ has a broken equality. How should it be fixed?",
    "@@user@@ has just bought a very ugly tracker. Describe how it would be used.",
    "How would @@user@@ treat a brutal how?",
    "Everyone enjoys a lodging. What is @@user@@'s like?",
    "@@user@@'s invention is selected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of oxygen. Describe it.",
    "Tell the story of how @@user@@ became wired.",
    "@@user@@ has a broken suspension. How should it be fixed?",
    "@@user@@ has just bought a very southern committee. Describe how it would be used.",
    "How would @@user@@ treat a founded reality?",
    "Everyone enjoys an anna. What is @@user@@'s like?",
    "@@user@@'s mailing is some. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of vibrator. Describe it.",
    "Tell the story of how @@user@@ became disturbed.",
    "@@user@@ has a broken wife. How should it be fixed?",
    "@@user@@ has just bought a very desired anatomy. Describe how it would be used.",
    "How would @@user@@ treat a sandy glucose?",
    "Everyone enjoys a nature. What is @@user@@'s like?",
    "@@user@@'s apollo is technical. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of funding. Describe it.",
    "Tell the story of how @@user@@ became weighted.",
    "@@user@@ has a broken manner. How should it be fixed?",
    "@@user@@ has just bought a very centered collecting. Describe how it would be used.",
    "How would @@user@@ treat a recovered kissing?",
    "Everyone enjoys a rep. What is @@user@@'s like?",
    "@@user@@'s industry is rural. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of chapel. Describe it.",
    "Tell the story of how @@user@@ became proud.",
    "@@user@@ has a broken elimination. How should it be fixed?",
    "@@user@@ has just bought a very demanding investor. Describe how it would be used.",
    "How would @@user@@ treat an incorrect coordinator?",
    "Everyone enjoys a where. What is @@user@@'s like?",
    "@@user@@'s notion is graphical. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of enforcement. Describe it.",
    "Tell the story of how @@user@@ became largest.",
    "@@user@@ has a broken inclusion. How should it be fixed?",
    "@@user@@ has just bought a very newest variance. Describe how it would be used.",
    "How would @@user@@ treat a compatible rand?",
    "Everyone enjoys a bacteria. What is @@user@@'s like?",
    "@@user@@'s relationship is reserved. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of notebook. Describe it.",
    "Tell the story of how @@user@@ became only.",
    "@@user@@ has a broken liability. How should it be fixed?",
    "@@user@@ has just bought a very numerical terror. Describe how it would be used.",
    "How would @@user@@ treat an awful pond?",
    "Everyone enjoys a connectivity. What is @@user@@'s like?",
    "@@user@@'s porno is centered. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of grid. Describe it.",
    "Tell the story of how @@user@@ became lonely.",
    "@@user@@ has a broken amplifier. How should it be fixed?",
    "@@user@@ has just bought a very decent strategy. Describe how it would be used.",
    "How would @@user@@ treat a cloudy personality?",
    "Everyone enjoys a jane. What is @@user@@'s like?",
    "@@user@@'s calculation is recorded. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of camera. Describe it.",
    "Tell the story of how @@user@@ became extensive.",
    "@@user@@ has a broken anatomy. How should it be fixed?",
    "@@user@@ has just bought a very incredible palace. Describe how it would be used.",
    "How would @@user@@ treat an arrested geography?",
    "Everyone enjoys an intake. What is @@user@@'s like?",
    "@@user@@'s life is graduated. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of algorithm. Describe it.",
    "Tell the story of how @@user@@ became threatening.",
    "@@user@@ has a broken contributor. How should it be fixed?",
    "@@user@@ has just bought a very discovered dick. Describe how it would be used.",
    "How would @@user@@ treat a same reservoir?",
    "Everyone enjoys a corruption. What is @@user@@'s like?",
    "@@user@@'s skill is needed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of resource. Describe it.",
    "Tell the story of how @@user@@ became pure.",
    "@@user@@ has a broken crossword. How should it be fixed?",
    "@@user@@ has just bought a very expanded bedding. Describe how it would be used.",
    "How would @@user@@ treat a renewable inline?",
    "Everyone enjoys an implementation. What is @@user@@'s like?",
    "@@user@@'s advertising is wanting. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of laundry. Describe it.",
    "Tell the story of how @@user@@ became elected.",
    "@@user@@ has a broken quad. How should it be fixed?",
    "@@user@@ has just bought a very congressional absorption. Describe how it would be used.",
    "How would @@user@@ treat a destroyed theta?",
    "Everyone enjoys an interval. What is @@user@@'s like?",
    "@@user@@'s element is huge. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of collection. Describe it.",
    "Tell the story of how @@user@@ became proposed.",
    "@@user@@ has a broken penalty. How should it be fixed?",
    "@@user@@ has just bought a very nasty discretion. Describe how it would be used.",
    "How would @@user@@ treat a toward cargo?",
    "Everyone enjoys a category. What is @@user@@'s like?",
    "@@user@@'s discovery is experienced. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of grid. Describe it.",
    "Tell the story of how @@user@@ became widespread.",
    "@@user@@ has a broken wrestling. How should it be fixed?",
    "@@user@@ has just bought a very ambient ranger. Describe how it would be used.",
    "How would @@user@@ treat a regulatory night?",
    "Everyone enjoys a livestock. What is @@user@@'s like?",
    "@@user@@'s canon is rational. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of sigma. Describe it.",
    "Tell the story of how @@user@@ became directed.",
    "@@user@@ has a broken denial. How should it be fixed?",
    "@@user@@ has just bought a very industrial laundry. Describe how it would be used.",
    "How would @@user@@ treat a busty thong?",
    "Everyone enjoys a thing. What is @@user@@'s like?",
    "@@user@@'s tsunami is industrial. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of ozone. Describe it.",
    "Tell the story of how @@user@@ became together.",
    "@@user@@ has a broken invasion. How should it be fixed?",
    "@@user@@ has just bought a very sporting pest. Describe how it would be used.",
    "How would @@user@@ treat a stunning advertiser?",
    "Everyone enjoys a writing. What is @@user@@'s like?",
    "@@user@@'s sept is remembered. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of tumor. Describe it.",
    "Tell the story of how @@user@@ became interracial.",
    "@@user@@ has a broken violin. How should it be fixed?",
    "@@user@@ has just bought a very varied victoria. Describe how it would be used.",
    "How would @@user@@ treat a presented anthropology?",
    "Everyone enjoys a pie. What is @@user@@'s like?",
    "@@user@@'s representation is awesome. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of violence. Describe it.",
    "Tell the story of how @@user@@ became animated.",
    "@@user@@ has a broken ejaculation. How should it be fixed?",
    "@@user@@ has just bought a very only realm. Describe how it would be used.",
    "How would @@user@@ treat a perceived option?",
    "Everyone enjoys an opposition. What is @@user@@'s like?",
    "@@user@@'s seller is democratic. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of casting. Describe it.",
    "Tell the story of how @@user@@ became oriented.",
    "@@user@@ has a broken valley. How should it be fixed?",
    "@@user@@ has just bought a very trusted marina. Describe how it would be used.",
    "How would @@user@@ treat a pending adapter?",
    "Everyone enjoys a phoenix. What is @@user@@'s like?",
    "@@user@@'s perspective is established. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of calculator. Describe it.",
    "Tell the story of how @@user@@ became massive.",
    "@@user@@ has a broken translation. How should it be fixed?",
    "@@user@@ has just bought a very enabling penguin. Describe how it would be used.",
    "How would @@user@@ treat an under ceremony?",
    "Everyone enjoys a civilization. What is @@user@@'s like?",
    "@@user@@'s compression is appointed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of earl. Describe it.",
    "Tell the story of how @@user@@ became entertaining.",
    "@@user@@ has a broken triangle. How should it be fixed?",
    "@@user@@ has just bought a very suited tech. Describe how it would be used.",
    "How would @@user@@ treat a treated basketball?",
    "Everyone enjoys an integration. What is @@user@@'s like?",
    "@@user@@'s tomato is focal. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of diameter. Describe it.",
    "Tell the story of how @@user@@ became filled.",
    "@@user@@ has a broken adoption. How should it be fixed?",
    "@@user@@ has just bought a very suspected why. Describe how it would be used.",
    "How would @@user@@ treat a worried she?",
    "Everyone enjoys a completion. What is @@user@@'s like?",
    "@@user@@'s crime is selective. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of operation. Describe it.",
    "Tell the story of how @@user@@ became afraid.",
    "@@user@@ has a broken passenger. How should it be fixed?",
    "@@user@@ has just bought a very sustainable skill. Describe how it would be used.",
    "How would @@user@@ treat a historical republic?",
    "Everyone enjoys an interface. What is @@user@@'s like?",
    "@@user@@'s nil is cultural. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of nat. Describe it.",
    "Tell the story of how @@user@@ became offshore.",
    "@@user@@ has a broken diary. How should it be fixed?",
    "@@user@@ has just bought a very gorgeous cam. Describe how it would be used.",
    "How would @@user@@ treat an easier chef?",
    "Everyone enjoys a compiler. What is @@user@@'s like?",
    "@@user@@'s victory is congressional. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of gaming. Describe it.",
    "Tell the story of how @@user@@ became apt.",
    "@@user@@ has a broken selection. How should it be fixed?",
    "@@user@@ has just bought a very empirical valentine. Describe how it would be used.",
    "How would @@user@@ treat a discrete safari?",
    "Everyone enjoys a colin. What is @@user@@'s like?",
    "@@user@@'s advertiser is experimental. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of ann. Describe it.",
    "Tell the story of how @@user@@ became else.",
    "@@user@@ has a broken preservation. How should it be fixed?",
    "@@user@@ has just bought a very enhanced duty. Describe how it would be used.",
    "How would @@user@@ treat an unable thanksgiving?",
    "Everyone enjoys a radar. What is @@user@@'s like?",
    "@@user@@'s stability is bacterial. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of precision. Describe it.",
    "Tell the story of how @@user@@ became handy.",
    "@@user@@ has a broken watershed. How should it be fixed?",
    "@@user@@ has just bought a very every grammar. Describe how it would be used.",
    "How would @@user@@ treat an incredible terror?",
    "Everyone enjoys an animation. What is @@user@@'s like?",
    "@@user@@'s mercury is greater. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of rhythm. Describe it.",
    "Tell the story of how @@user@@ became outdoor.",
    "@@user@@ has a broken recovery. How should it be fixed?",
    "@@user@@ has just bought a very collaborative lung. Describe how it would be used.",
    "How would @@user@@ treat a dispatched passenger?",
    "Everyone enjoys a renaissance. What is @@user@@'s like?",
    "@@user@@'s herb is dense. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of location. Describe it.",
    "Tell the story of how @@user@@ became governmental.",
    "@@user@@ has a broken porno. How should it be fixed?",
    "@@user@@ has just bought a very adopted jewelry. Describe how it would be used.",
    "How would @@user@@ treat an alike clearance?",
    "Everyone enjoys a literature. What is @@user@@'s like?",
    "@@user@@'s pursuit is pregnant. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of concentration. Describe it.",
    "Tell the story of how @@user@@ became deadly.",
    "@@user@@ has a broken doctrine. How should it be fixed?",
    "@@user@@ has just bought a very attempted biz. Describe how it would be used.",
    "How would @@user@@ treat a numerous beth?",
    "Everyone enjoys a journalist. What is @@user@@'s like?",
    "@@user@@'s mixer is corresponding. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of diesel. Describe it.",
    "Tell the story of how @@user@@ became governmental.",
    "@@user@@ has a broken tribute. How should it be fixed?",
    "@@user@@ has just bought a very cute mon. Describe how it would be used.",
    "How would @@user@@ treat a declared dealer?",
    "Everyone enjoys a valuation. What is @@user@@'s like?",
    "@@user@@'s bee is greater. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of terrain. Describe it.",
    "Tell the story of how @@user@@ became empirical.",
    "@@user@@ has a broken theory. How should it be fixed?",
    "@@user@@ has just bought a very psychological when. Describe how it would be used.",
    "How would @@user@@ treat a geological permission?",
    "Everyone enjoys a lat. What is @@user@@'s like?",
    "@@user@@'s bankruptcy is structural. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of symphony. Describe it.",
    "Tell the story of how @@user@@ became forbidden.",
    "@@user@@ has a broken taxation. How should it be fixed?",
    "@@user@@ has just bought a very tall reporter. Describe how it would be used.",
    "How would @@user@@ treat a larger wrist?",
    "Everyone enjoys an ambassador. What is @@user@@'s like?",
    "@@user@@'s poker is innovative. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of ending. Describe it.",
    "Tell the story of how @@user@@ became intelligent.",
    "@@user@@ has a broken inclusion. How should it be fixed?",
    "@@user@@ has just bought a very older festival. Describe how it would be used.",
    "How would @@user@@ treat an alone builder?",
    "Everyone enjoys an unemployment. What is @@user@@'s like?",
    "@@user@@'s compilation is after. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of embassy. Describe it.",
    "Tell the story of how @@user@@ became sonic.",
    "@@user@@ has a broken prediction. How should it be fixed?",
    "@@user@@ has just bought a very acceptable confirmation. Describe how it would be used.",
    "How would @@user@@ treat a matching transparency?",
    "Everyone enjoys a monster. What is @@user@@'s like?",
    "@@user@@'s consortium is sandy. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of johnny. Describe it.",
    "Tell the story of how @@user@@ became disturbed.",
    "@@user@@ has a broken hierarchy. How should it be fixed?",
    "@@user@@ has just bought a very rejected separation. Describe how it would be used.",
    "How would @@user@@ treat a collaborative cooler?",
    "Everyone enjoys a replacement. What is @@user@@'s like?",
    "@@user@@'s religion is dangerous. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of declaration. Describe it.",
    "Tell the story of how @@user@@ became industrial.",
    "@@user@@ has a broken palmer. How should it be fixed?",
    "@@user@@ has just bought a very recommended outlook. Describe how it would be used.",
    "How would @@user@@ treat a pregnant magazine?",
    "Everyone enjoys an intelligence. What is @@user@@'s like?",
    "@@user@@'s architect is geographical. How would @@user@@ resolve this?"
];

foreach ($mike_questions as $mike_question) {

    $q = new stdClass();
    $q->text = $mike_question;
    $q->game_type = 4;
    create_question($q);
}
