<?php


$mike_questions = [
    "@@user@@ invented a new type of quantity. Describe it.",
    "Tell the story of how @@user@@ became organizational.",
    "@@user@@ has a broken perry. How should it be fixed?",
    "@@user@@ has just bought a very compliant librarian. Describe how it would be used.",
    "How would @@user@@ treat an obvious indication?",
    "Everyone enjoys a scholarship. What is @@user@@'s like?",
    "@@user@@'s millennium is strange. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of subsection. Describe it.",
    "Tell the story of how @@user@@ became vocational.",
    "@@user@@ has a broken importance. How should it be fixed?",
    "@@user@@ has just bought a very historical strategy. Describe how it would be used.",
    "How would @@user@@ treat a compressed storage?",
    "Everyone enjoys an earl. What is @@user@@'s like?",
    "@@user@@'s allocation is projected. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of def. Describe it.",
    "Tell the story of how @@user@@ became pregnant.",
    "@@user@@ has a broken deadline. How should it be fixed?",
    "@@user@@ has just bought a very cellular conclusion. Describe how it would be used.",
    "How would @@user@@ treat an effective flyer?",
    "Everyone enjoys a fusion. What is @@user@@'s like?",
    "@@user@@'s characterization is occupied. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of city. Describe it.",
    "Tell the story of how @@user@@ became athletic.",
    "@@user@@ has a broken admission. How should it be fixed?",
    "@@user@@ has just bought a very wanting tractor. Describe how it would be used.",
    "How would @@user@@ treat an eastern atmosphere?",
    "Everyone enjoys a maple. What is @@user@@'s like?",
    "@@user@@'s winner is ongoing. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of particle. Describe it.",
    "Tell the story of how @@user@@ became authentic.",
    "@@user@@ has a broken uncertainty. How should it be fixed?",
    "@@user@@ has just bought a very called movement. Describe how it would be used.",
    "How would @@user@@ treat an animated advancement?",
    "Everyone enjoys a physician. What is @@user@@'s like?",
    "@@user@@'s colleague is documented. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of literature. Describe it.",
    "Tell the story of how @@user@@ became proud.",
    "@@user@@ has a broken greenhouse. How should it be fixed?",
    "@@user@@ has just bought a very worried treaty. Describe how it would be used.",
    "How would @@user@@ treat a dated gnome?",
    "Everyone enjoys a distinction. What is @@user@@'s like?",
    "@@user@@'s porter is pleased. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of hall. Describe it.",
    "Tell the story of how @@user@@ became fascinating.",
    "@@user@@ has a broken paradise. How should it be fixed?",
    "@@user@@ has just bought a very underlying bibliography. Describe how it would be used.",
    "How would @@user@@ treat a destroyed billy?",
    "Everyone enjoys an explosion. What is @@user@@'s like?",
    "@@user@@'s volume is exciting. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of declaration. Describe it.",
    "Tell the story of how @@user@@ became different.",
    "@@user@@ has a broken modeling. How should it be fixed?",
    "@@user@@ has just bought a very packed reality. Describe how it would be used.",
    "How would @@user@@ treat an used semester?",
    "Everyone enjoys an adjustment. What is @@user@@'s like?",
    "@@user@@'s addition is expanded. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of who. Describe it.",
    "Tell the story of how @@user@@ became powered.",
    "@@user@@ has a broken wedding. How should it be fixed?",
    "@@user@@ has just bought a very inherited timothy. Describe how it would be used.",
    "How would @@user@@ treat an implemented merger?",
    "Everyone enjoys a dealer. What is @@user@@'s like?",
    "@@user@@'s graduation is formed. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of crossword. Describe it.",
    "Tell the story of how @@user@@ became pleasant.",
    "@@user@@ has a broken plaintiff. How should it be fixed?",
    "@@user@@ has just bought a very unlikely text. Describe how it would be used.",
    "How would @@user@@ treat an everyday municipality?",
    "Everyone enjoys a spider. What is @@user@@'s like?",
    "@@user@@'s sword is behavioral. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of batman. Describe it.",
    "Tell the story of how @@user@@ became tiny.",
    "@@user@@ has a broken fiction. How should it be fixed?",
    "@@user@@ has just bought a very needed checklist. Describe how it would be used.",
    "How would @@user@@ treat a developmental elevation?",
    "Everyone enjoys a version. What is @@user@@'s like?",
    "@@user@@'s roller is everyday. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of when. Describe it.",
    "Tell the story of how @@user@@ became attended.",
    "@@user@@ has a broken surveillance. How should it be fixed?",
    "@@user@@ has just bought a very lowest signature. Describe how it would be used.",
    "How would @@user@@ treat a pointed valuation?",
    "Everyone enjoys a placement. What is @@user@@'s like?",
    "@@user@@'s intro is requested. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of formation. Describe it.",
    "Tell the story of how @@user@@ became applied.",
    "@@user@@ has a broken ocean. How should it be fixed?",
    "@@user@@ has just bought a very residential polyester. Describe how it would be used.",
    "How would @@user@@ treat a dimensional turkey?",
    "Everyone enjoys a spider. What is @@user@@'s like?",
    "@@user@@'s norm is ethical. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of integer. Describe it.",
    "Tell the story of how @@user@@ became pleasant.",
    "@@user@@ has a broken someone. How should it be fixed?",
    "@@user@@ has just bought a very metallic hygiene. Describe how it would be used.",
    "How would @@user@@ treat a polyphonic calling?",
    "Everyone enjoys an education. What is @@user@@'s like?",
    "@@user@@'s contacting is available. How would @@user@@ resolve this?",
    "@@user@@ invented a new type of connectivity. Describe it.",
    "Tell the story of how @@user@@ became healthy.",
    "@@user@@ has a broken arcade. How should it be fixed?",
    "@@user@@ has just bought a very remembered nothing. Describe how it would be used.",
    "How would @@user@@ treat a considered location?",
    "Everyone enjoys a thou. What is @@user@@'s like?",
    "@@user@@'s chapel is rational. How would @@user@@ resolve this?"
];


foreach ($mike_questions as $mike_question) {

    $q = new stdClass();
    $q->text = $mike_question;
    $q->game_type = 2;
    create_question($q);
}
